// AUTO-GENERATED by src/themes/generate.ts — do not edit by hand.
// Regenerated on every build from the theme files in this directory.
import type { ThemeDefinition } from './types.ts'
import t0 from './catppuccin.ts'
import t1 from './dracula.ts'
import t2 from './github.ts'
import t3 from './nord.ts'
import t4 from './one-dark.ts'
import t5 from './perplexity.ts'
import t6 from './solarized.ts'
import t7 from './tokyo-night-storm.ts'
import t8 from './tokyo-night.ts'
import t9 from './transparent-perplexity.ts'
import t10 from './zinc.ts'

export const THEME_DEFS: ThemeDefinition[] = [t0, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10]
