// AUTO-GENERATED by src/themes/generate.ts — do not edit by hand.
// Regenerated on every build from the theme files in this directory.
import type { ThemeDefinition } from './types.ts'
import t0 from './perplexity.ts'
import t1 from './transparent-perplexity.ts'

export const THEME_DEFS: ThemeDefinition[] = [t0, t1]
