// ============================================================================
// Theme registry generator (build-time, Bun only).
//
// Scans src/themes/*.ts for theme files and writes _registry.generated.ts,
// which statically imports each theme's default export into a THEME_DEFS array.
// The static-import file is what gets bundled for the browser (Bun.Glob can't
// run in-browser), so this regeneration step is what makes "drop a file →
// rebuild → it appears" work without hand-editing any list.
//
// Called at the top of bm-editor.ts / bm-preview.ts before Bun.build().
// ============================================================================

import { Glob } from 'bun'

const HERE = new URL('.', import.meta.url).pathname
const GENERATED = `${HERE}_registry.generated.ts`

// Files in this directory that are infrastructure, not themes.
const NON_THEME = new Set(['types.ts', 'index.ts', 'generate.ts', '_registry.generated.ts'])

/**
 * Discover theme files and (re)write _registry.generated.ts. Returns the list
 * of discovered theme module basenames (without extension), sorted.
 */
export async function generateThemeRegistry(): Promise<string[]> {
  const glob = new Glob('*.ts')
  const files: string[] = []
  for await (const file of glob.scan({ cwd: HERE })) {
    if (!NON_THEME.has(file)) files.push(file)
  }
  files.sort()

  const imports = files
    .map((f, i) => `import t${i} from './${f.replace(/\.ts$/, '.ts')}'`)
    .join('\n')
  const arr = files.map((_, i) => `t${i}`).join(', ')

  const out = `// AUTO-GENERATED by src/themes/generate.ts — do not edit by hand.
// Regenerated on every build from the theme files in this directory.
import type { ThemeDefinition } from './types.ts'
${imports}

export const THEME_DEFS: ThemeDefinition[] = [${arr}]
`

  await Bun.write(GENERATED, out)
  return files.map((f) => f.replace(/\.ts$/, ''))
}
